### ISSUE TITLE
`DataProduct` table has a `OneToOneField` relationship with `Object` - should be `ForeignKey`

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#118]

**Comment by alahiff** [comment]
Won't this have big consequences on https://github.com/FAIRDataPipeline/data-registry/blob/main/templates/data_management/object_detail.html? In particular it assumes that:
* there is a single, unique data product associated with an object
* there is a single, unique external object associated with a data product

If this is no longer true we need to create new details pages for data products and external objects, rather than just use an object for anything (maybe this is the right thing to do?)

**Comment by richardreeve** [comment]
Hmm. It was always intended that multiple data products could refer to the same object I'm afraid. For an example of where this is really important, if we have a data product that we make v1.0-rc1, and then it turns out to have no problems so we release it as v1.0.

These are the same object, and in particular if we identify an issue with one data product, it's an issue with the other. Since issues are associated with objects (well, object components), the two data products have to refer to the same object otherwise an issue with one will incorrectly not be associated with the other.

**Comment by alahiff** [comment]
Created an issue: https://github.com/FAIRDataPipeline/data-registry/issues/119

**Comment by richardreeve** [comment]
I guess we can move forward on this now @alahiff. If so, can we do it without affecting the Registry (REST) API, or does there have to be a change to it? Obviously if we can do it without any changes to that API, then we're golden, but if not we need to coordinate with Sonia and the rest of the DPAPI crew when we make the change...

**Comment by alahiff** [comment]
There will be one change - in `/api/object` the read-only field `data_product` (a single item) will change to `data_products` (a list).

**Comment by richardreeve** [comment]
Okay, if it's read-only at least that means that it won't affect creating any new entries (presumably?). @soniamitchell - do you use this `/api/object` - `data_product` field anywhere?

**Comment by alahiff** [comment]
I can confirm that there are no issues with existing data (i.e. data products) after this change is implemented. There are no changes in the way that new data products are created.

**Comment by soniamitchell** [comment]
> Okay, if it's read-only at least that means that it won't affect creating any new entries (presumably?). @soniamitchell - do you use this `/api/object` - `data_product` field anywhere?

I don't believe I do, not in the obvious places anyway!

**Comment by richardreeve** [comment]
Great, then I guess we can go ahead with this too...
