### ISSUE TITLE
Changes to StorageRoot

### ISSUE THREAD

**Issue by alahiff** [FAIRDataPipeline/data-registry#56]
Need to add a Boolean indicating if the `StorageRoot` is local or not. Field name could be `localroot` or just `local`. By default it should be set to `False`.

**Comment by alahiff** [comment]
Also we need to drop `accessibility` and add a Boolean `public`

**Comment by alahiff** [comment]
Changes are in the `storage_root_changes` branch: https://github.com/ScottishCovidResponse/data-registry/tree/storage_root_changes

**Comment by alahiff** [comment]
Any uniqueness constraints should probably involve both `local` and `public`, as users might want to use the same local storage system for both local and "non-local" files, and both private and public files.

**Comment by richardreeve** [comment]
@alahiff - can we make a PR out of that, so it's easier to see what has changed? As far as the uniqueness constraint is concerned, isn't `public` in `StorageLocation` rather than in `StorageRoot` though, so there are two uniqueness constraints, one in `StorageLocation` that is (_hash_, _public_), and one in `StorageRoot`, that  is (_root_, _local_)? And I think we were going to drop _name_ for now, since we didn't have an obvious use for it?

**Comment by alahiff** [comment]
Summary of changes in the pull request:
* `name` field removed from `StorageRoot`
* `accessibility` field removed from `StorageRoot`
* `local` flag added to `StorageRoot`
* uniqueness constraint on (`root` and `local`) in `StorageRoot` (i.e. you can have the same storage root for both local and non-local files)
* `public` flag added to `StorageLocation`
* uniqueness constraint on (`storage_root`, `hash`, `path`, `public`) in `StorageLocation`
