### ISSUE TITLE
Add identifier in Keyword

### ISSUE THREAD

**Issue by agbeltran** [FAIRDataPipeline/data-registry#76]
In orde to support keywords to be ontology annotations, we should add an ```identifier``` field.

Or is the ```url``` field fulfilling this purpose? If so, I would rename it to ```identifier```

https://github.com/ScottishCovidResponse/data-registry/blob/8640beba7bb538bff0000fa3ccb71302ce88501a/data_management/models.py#L618

**Comment by agbeltran** [comment]
cc @alahiff

**Comment by alahiff** [comment]
The `url` field read-only and is the URL of the API endpoint corresponding to the keyword itself, e.g.
```
$ curl https://data.scrc.uk/api/keyword/104315/ | jq .
{
  "url": "https://data.scrc.uk/api/keyword/104315/",
  "last_updated": "2020-08-20T19:30:16.914282Z",
  "keyphrase": "non-human primate animal model",
  "updated_by": "https://data.scrc.uk/api/users/3/",
  "object": "https://data.scrc.uk/api/object/41056/"
}
```

**Comment by agbeltran** [comment]
thanks @alahiff , then in preparation for having ontology annotations (so that we prepare for FAIR data), we need an ```identifier``` field too.

for the example, the ```identifier``` could be the term  ```non-human primate``` from this ontology:
https://bioportal.bioontology.org/ontologies/BIRNLEX?p=classes&conceptid=http%3A%2F%2Fbioontology.org%2Fprojects%2Fontologies%2Fbirnlex%23birnlex_603

this is just an example, we will need to work on what ontologies to recommend for annotations

**Comment by alahiff** [comment]
Implemented in https://github.com/ScottishCovidResponse/data-registry/commit/ef8d40614700d4893a0d12cd53c33bacdc6f6d1a. @agbeltran you may possibly want to adjust the description of what `identifier` actually means in case what I wrote is not quite correct.

I used `URLField` for this so that only valid URLs will be accepted. I changed the identifier in `Author` and `Organisation` to be consistent with this in https://github.com/ScottishCovidResponse/data-registry/commit/a29fd9b3f8d5792535abfeb1dba96b6a786df235

**Comment by alahiff** [comment]
Closing as it has been implemented. The docs can be tweaker later at any point if necessary.
