### ISSUE TITLE
Should ExternalObject unique in the context of `doi_or_unique_name`, `title`, and the DataProduct `version`?

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/data-registry#87]
Could we make a read only version field in ExternalObject that links to DataProduct version?

**Comment by richardreeve** [comment]
At the moment we have `doi_or_unique_name` and `title` as the uniqueness constraints. A couple of questions:

1. Do we want to keep `doi_or_unique_name`?
   - Or do we want to split it up into an optional `doi` and an optional `other_unique_name` (and make the constraint on the combination) so that we know what kind of thing it is?
   - Or alternatively do we want to go to an `identifier` url option like for author, so that we can include other unique identifiers like arXiv ids, ones from government databases, etc.? If we do that, do we want to separate out `other_unique_name` still as a non-url?
2. Do we want to include `version` as a uniqueness constraint? If so, it doesn't currently exist, so is it the version from the data product? We said yes to moving the version into the data product version a few weeks ago, but maybe that will be problematic if some non-DOI unique identifiers have versions of their own?

It would be good to have @agbeltran / @antony-wilson 's thoughts on this, as we may be stuck with it for a while after we make this decision...

**Comment by alahiff** [comment]
Currently `DataProduct` has a uniqueness constraint on `namespace`, `name`, `version`. Just to be clear, we need to keep this constraint, but also have a constraint in `ExternalObject` on `version` and (`identifier` or `other_unique_name`), where the `version` field is the same in both `DataProduct` and `ExternalObject`?

**Comment by richardreeve** [comment]
We have a constraint in `ExternalObject` on `version` and (`identifier` or `other_unique_name`) and `title`. When we create an external object we don't specify the version, it just copies it from its data product.

I think if we decide down the road to allow external objects to have their own versions, then we can add in an optional `version` argument - if it's not entered then it will take it from the data product, so we'll have backward compatibility.

Does that all seem like it'll work?

**Comment by alahiff** [comment]
In a branch I've made some changes (https://github.com/FAIRDataPipeline/data-registry/commit/76d7799a0ebdd1bf8f96d6501c46f3245001a32a) so that `ExternalObject` now has a non-editable `version` field where the value is taken from the `DataProduct`. If in future it's decided that external objects can have their own version, we just need to remove the `editable=False` and adjust the documentation.

(Nathan is doing the other changes which is why I left them as they were).

**Comment by alahiff** [comment]
I've moved my changes (i.e. adding the version) into Nathan's pull request https://github.com/FAIRDataPipeline/data-registry/pull/92 to simplify things.

**Comment by nathan-cummings-ukaea** [comment]
This can be closed as well now I guess?
