### ISSUE TITLE
Remote registry and GDPR

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#90]
Following a discussion I just raised with @alysbrett, I wanted to ask about whether or not we need to take a careful look at the GDPR implications of the sort of data that the remote registry is storing.

Now that we have tables for users, authors, organisations etc... we are almost certainly storing personal information (ie, enough to uniquely identify someone). Even though we expect such data to be already publicly available elsewhere, we do allow users to upload data from their local registry. We are allowing users to upload other people's personal information without their explicit consent, and are not necessarily ensuring that the user has obtained that data from a public source.

Obviously, I am no expert in this, and the project leaders may already be on top of this (@richardreeve?), and there is no need to worry, but I feel like it is a question worth asking now rather than risking some embarrassment (at the very least!) somewhere down the line.

**Comment by richardreeve** [comment]
We are thinking about this, and it is definitely a worry.

One specific concern that has been raised is that we may connect authors to organisations in a way that may not be public, e.g. identifying someone as coming from an organisation that is not public, like issues we had previously with AWE. One possible solution to that is to remove the linkage between authors and organisation completely, and just have an author table that can link either to the org that produced the data (via their ROR) or the person who produced it (via their ORCID).

This would actually simplify quite a lot of things (we wouldn't have to worry about people with multiple affiliations, for instance). Does anyone have a thought about any potential problems with that (e.g. @nathan-cummings-ukaea / @alahiff / @soniamitchell / @DennisReddyhoff)? If a person's ORCID publicly released their organisational affiliations through the API (@agbeltran / @antony-wilson do you know if that is part of the API?), then that information could be recovered, but otherwise it would be private.

The other thing to bear in mind is that overwhelmingly we don't know the organisational affiliation for most people (e.g. from papers) or the people who published stuff that comes from organisations, so mostly one of the two entries in the AuthorOrg combo is empty anyway...

**Comment by richardreeve** [comment]
The actual work to change this might be:

- to remove the organisation table completely
- allow an organisation name in the Author table
- allow RORs, etc. in the identifier field of Author, but I think that's possible already?
- Change ObjectAuthorOrg to ObjectAuthor (and drop org)
- Change UserAuthorOrg to User Author (and drop orgs)

**Comment by soniamitchell** [comment]
It seems ok to me.. though I struggle to visualise things without implementing them. Are you saying that the `identifier` field should now take a list of URLs, in which case how do you differentiate between the two? Or are you saying that we have to choose between adding an orcid id and ror id?

**Comment by richardreeve** [comment]
The latter. Either the author is an org, in which case you put in a ROR id, or it’s a person and you put in an ORCID.

**Comment by soniamitchell** [comment]
Do we not want both? – I'm not really familiar with ROR ids so not sure when I'd use them..

**Comment by richardreeve** [comment]
No, the old idea included both so I could say I was from Glasgow and SCRC (for instance). The *new* idea is we only use ORCIDs for actual humans (so something I author is just from me), and we only use RORs when the data just comes from an org like ONS.

**Comment by soniamitchell** [comment]
So you'll have multiple UserAuthorOrg entries? One with your ORCID id (person), another for UoG, and another for SCRC? Presumably you'll need another field in the config to specify whether you're yourself or a specific organisation. It's still not clear (to me) how this would work.

**Comment by nathan-cummings-ukaea** [comment]
I'll let Andrew comment on what he thinks of the change, as the all the user/author/organisation related tables were his developments.

It sounds like what you are proposing may help mitigate GDPR issues. I'm still a little concerned about whether what we store (even if we have obtained it from a public source, like ORCHID) still constitutes personal data, and what we are required to have in place to be compliant, such as facilitating the right for someone to see what data we hold about them, and the right to remove any data about them if they want.

Again, I stress that I am no expert in any of this, and if someone knows a good DPO it might be worth us consulting with them perhaps?

**Comment by richardreeve** [comment]
> So you'll have multiple UserAuthorOrg entries? One with your ORCID id (person), another for UoG, and another for SCRC? Presumably you'll need another field in the config to specify whether you're yourself or a specific organisation. It's still not clear (to me) how this would work.

No, not at all. I'll just be me. I will have an ORCID, but I won't be associated with an org at all as far as the registry is concerned. There will just be a `UserAuthor` entry that you can search to find who I am based on my userid just like you could before with the `UserAuthorOrg` table. Now you'll just need to add that entry to the `ObjectAuthor` table, just like previously you did with multiple entries to the `ObjectAuthorOrg` entries. Does that make sense?

**Comment by richardreeve** [comment]
> I'll let Andrew comment on what he thinks of the change, as all the user/author/organisation related tables were his developments.
> 
> It sounds like what you are proposing may help mitigate GDPR issues. I'm still a little concerned about whether what we store (even if we have obtained it from a public source, like ORCHID) still constitutes personal data, and what we are required to have in place to be compliant, such as facilitating the right for someone to see what data we hold about them, and the right to remove any data about them if they want.
> 
> Again, I stress that I am no expert in any of this, and if someone knows a good DPO it might be worth us consulting with them perhaps?

@nathan-cummings-ukaea These are all good points, and we have someone looking into the more general GDPR implications of the remote registry (so doing this won't close this issue, sadly!). However, this was flagged up as the only place we could immediately identify where we were actually _adding_ information (the association between a user and their organisation), which might be more problematic that other compliance issues.

**Comment by richardreeve** [comment]
@soniamitchell Just to follow up on that, if I was pretending to be Open Data Scotland (say I have a cron job running to pull in updates like you had before), then the `UserAuthor` table would just connect the `admin` user to the `ODS` author in the Author table, which would have ODS's ROR url attached to it (instead, say, of my ORCID url). We can tell it's a ROR and not an ORCID because the url's domain will be ror.org rather than orcid.org.

**Comment by alahiff** [comment]
> allow an "organisation name" field in the Author table

Is this as an alternative to `family_name` and `given_name`?

Another way could be to replace `family_name` and `given_name` with `name`, which could then be either a person or organisation. The government seems to suggest using a full name only as it's more inclusive (https://design-system.service.gov.uk/patterns/names/).

**Comment by richardreeve** [comment]
I was thinking of it as one or the other, yes, but your suggestion is interesting. It makes sense. We will have some confusion about whether we have a person or an organisation if they don't have an identifier, or if we don't know what the identifier refers to. We also won't be able to search by family name. I don't know whether either of those are important though - it would certainly make things simpler.

I think we may need a ruling(!) from the metadata side - @agbeltran, what do you think?

Would a single `name` be okay for interoperability - together with `identifier` - or should we stick with (`family_name`,`given_name`) | `organisation_name`? Or is there some other way we could do this? A boolean to say which it is? We don't have to change what we currently have, but the truth is we will very rarely have both pieces of information - essentially only for ourselves I think. And I don't know whether there are GDPR implications of attaching these pieces of information together.

**Comment by alahiff** [comment]
You could still easily search by family name, e.g.
```
/api/author/?name=*Johnson
```

Instead of a boolean to say which it is another option would be to have something like `type` which has values `person` or `organisation`.

**Comment by alahiff** [comment]
If we're going to drop the `Organisation` table we can also drop the `ObjectAuthorOrg` table and go back to doing what we did originally and just allow a list of authors to be directly attached to an `Object`.

**Comment by richardreeve** [comment]
But with a `uuid`, `identifier` and `name`, and with at least one of `identifier` and `name` present as the unique key?

**Comment by alahiff** [comment]
To be more precise, before we specifed an `Object` for each entry in the `Author` table and had a read-only `authors` field in `Object`. I was thinking of doing it in the opposite direction - in the `Object` specify an optional writeable list of authors. That way it's fine for authors to be unique, and a single author can be used for multiple objects.

**Comment by richardreeve** [comment]
Yes, that sounds good. I remembered there was something wrong about how we had the authors done before that stopped us getting unique identifiable authors, but this plan sounds like it fixes it. Presumably we still need a UserAuthor table because you can't edit the underlying user table, or can you do that too?

**Comment by alahiff** [comment]
We can modify the underlying user table, and have actually done this - it has full names, email addresses and organisations included, and these are linked to the userids. This only applies to the remote registry where the information is taken from the external MySQL user database. This information is only available to people who are logged in so it's not publicly accessible.

Do we actually need this information? I'm not sure about the GDPR implications of this since it's not public, but people who can login can see information about everybody else who has access.

Note that the implemention of this is SCRC-specific since it depends on an external database, so it's not ideal if we expect other people to setup (remote) data registries at some point.

**Comment by nathan-cummings-ukaea** [comment]
> We can modify the underlying user table, and have actually done this - it has full names, email addresses and organisations included, and these are linked to the userids. This only applies to the remote registry where the information is taken from the external MySQL user database. This information is only available to people who are logged in so it's not publicly accessible.
> 
> Do we actually need this information? I'm not sure about the GDPR implications of this since it's not public, but people who can login can see information about everybody else who has access.
> 
> Note that the implemention of this is SCRC-specific since it depends on an external database, so it's not ideal if we expect other people to setup (remote) data registries at some point.

If we're only talking about people who are/were SCRC members, do I recall that we sign some kind of agreement last year that likely covers this?

**Comment by alahiff** [comment]
> If we're only talking about people who are/were SCRC members, do I recall that we sign some kind of agreement last year that likely covers this?

It's people who are/were SCRC members and who have explicitly logged into the data registry at least once.

**Comment by richardreeve** [comment]
Ah, if the user table is different between the remote registry and the local registry (which makes complete sense), it probably makes more sense for there to be a separate UserAuthor table which contains that specific connection between userid and author still, like the UserAuthorOrg table does at the moment.

As far as taking that information from the MySQL database, we definitely want to drop that at some point for practical reasons (for other people to set up a remote registry) as well as GDPR ones. We probably need to sort that out when we sort out how authentication with the remote registry works more generally.

**Comment by alahiff** [comment]
Pull request created: https://github.com/FAIRDataPipeline/data-registry/pull/100

**Comment by richardreeve** [comment]
Presumably `identifier` only has to be unique if it's non-null?

**Comment by alahiff** [comment]
Yes, that's correct (and I've checked it).

**Comment by richardreeve** [comment]
Cool, so does #100 close this then?

**Comment by alahiff** [comment]
Yes

**Comment by alahiff** [comment]
Closing since https://github.com/FAIRDataPipeline/data-registry/pull/100 has been merged
